# DB config : skal pege til ../whoknows.db
# Database connection settings

# Kan udkommenteres n√•r db skal bruges
#development:
  #adapter: sqlite3
  #database: ../whoknows.db

development:
  adapter: sqlite3
  database: ../whoknows.db
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: ":memory:"
  pool: 5
  timeout: 5000